export const LOGIN_USER_TYPE = 'USER/LOGIN_USER';
export const REGISTER_USER_TYPE = 'USER/REGISTER_USER';
export const VERIFY_USER_TYPE = 'USER/VERIFY_USER';
export const FORGOT_PASSWORD_TYPE = 'USER/FORGOT_PASSWORD';
export const RESET_PASSWORD_TYPE = 'USER/RESET_PASSWORD';
